name: WhiteList

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "35 20 * * *"
    

env:
  REPO_URL: https://github.com/v2fly/domain-list-community
  REPO_BRANCH: master
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@main
      
    - name: Clone domain list
      if: ( !cancelled() )
      id: clone
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        cd /workdir
        git clone $REPO_URL -b $REPO_BRANCH domainlist
        ln -sf /workdir/domainlist $GITHUB_WORKSPACE/domainlist
        
    - name: Organize Files
      id: organize
      if: ( !cancelled() )
      run: |
        bash WhiteList.sh
        python3 -m base64 WhiteList.tmp &> WhiteList.txt
        today=`date`
        git config --local user.email "93760897+0xHO@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit WhiteList.txt -m "update ${today}"

    - name: Push changes
      if: ( !cancelled() )
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main

    - name: Delete Workflow Runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 8
