name: WhiteList

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "35 20 * * *"
    

env:
  REPO_URL: https://github.com/v2fly/domain-list-community
  REPO_BRANCH: master
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@main
      
    - name: Clone domain list
      if: ( !cancelled() )
      id: clone
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        cd /workdir
        git clone $REPO_URL -b $REPO_BRANCH domainlist
        
        
    - name: Organize Files
      id: organize
      if: ( !cancelled() )
      run: |
        today=`date`
        cat WhiteList.sh > /tmp/WhiteList.sh
        cat service.sh > /tmp/service.sh
        git checkout assets
        cat /tmp/WhiteList.sh > WhiteList.sh
        cat /tmp/service.sh > service.sh
        ln -sf /workdir/domainlist $GITHUB_WORKSPACE/domainlist
        bash WhiteList.sh
        python3 -m base64 WhiteList.tmp &> WhiteList.txt
        cat ssc.tmp > ss.conf
        git config --local user.email "93760897+0xHO@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit WhiteList.txt ss.conf dnsmasq.conf -m "update WhiteList ${today}"
        # bash service.sh "service file 
        mkdir -p service
        bash service.sh "openai"
        bash service.sh "microsoft" microsoft "xbox\|github"
        bash service.sh "apple icloud" apple
        bash service.sh "category-games" games bilibili
        bash service.sh "category-games@cn" gamesCN
        bash service.sh "category-entertainment" entertainments
        bash service.sh "geolocation-cn" cn
        bash service.sh "anthropic"
        bash service.sh "oracle" 
        bash service.sh "github"
        git add service/*
        rm -rf WhiteList.sh service.sh
        git commit service/* -m "update Service ${today}"

    - name: Push changes
      if: ( !cancelled() )
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: assets

    - name: Delete Workflow Runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 8