name: WhiteList

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "35 20 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@main
      with:
        ref: assets
      
    - name: Clone domain list
      if: ( !cancelled() )
      id: clone
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        git config --local user.email "93760897+0xHO@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        cd /workdir
        git clone https://github.com/v2fly/domain-list-community  domainlist

    - name: Checkout Main Code
      if: ( !cancelled() )
      uses: actions/checkout@main
      with:
         path: main

    - name: Organize Files
      id: organize
      if: ( !cancelled() )
      run: |
        today=`date`
        ls -al
        ln -sf /workdir/domainlist main/domainlist
        cd main
        bash WhiteList.sh
        python3 -m base64 WhiteList.tmp &> ../WhiteList.txt
        cat ssc.tmp > ../ss.conf

        echo "# Service: gfwlist" > ../service/gfwlist.yaml
        echo "# from: https://github.com/gfwlist/gfwlist" >> ../service/gfwlist.yaml
        echo "# Repo: https://github.com/0xHO/WhiteList/blob/assets/service/gfwlist.yaml" >> ../service/gfwlist.yaml
        echo "# raw: https://raw.githubusercontent.com/0xHO/WhiteList/assets/service/gfwlist.yaml" >> ../service/gfwlist.yaml
        echo "# raw: https://cdn.jsdelivr.net/gh/0xHO/WhiteList@assets/service/gfwlist.yaml" >> ../service/gfwlist.yaml
        echo "# raw: https://ghproxy.com/https://raw.githubusercontent.com/0xHO/WhiteList/assets/service/gfwlist.yaml" >> ../service/gfwlist.yaml
        echo "# Update: ${today}" >> ../service/gfwlist.yaml
        echo "payload:" >> ../service/gfwlist.yaml
        curl https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt|base64 -d|grep -v "^@"|grep -v "^\!"|grep -v \/|grep -v "^$"|grep -v "*"|grep -v "%"|grep -v "\[" |grep -v "="|grep -v -E ".[0-9]{1,3}$"|sed "s/^\.//g"|sed "s/^||//g"|sed "s/^\|\|//g"|sort|uniq|sed "s/^/   - DOMAIN-SUFFIX,/g" >> ../service/gfwlist.yaml


        # bash service.sh "service file 
        bash service.sh "openai" &> ../service/openai.yaml
        echo "   - DOMAIN-SUFFIX,sentry.io" >> ../service/openai.yaml
        echo "   - DOMAIN-SUFFIX,stripe.com" >> ../service/openai.yaml
        bash service.sh "microsoft" microsoft "xbox\|github" &> ../service/microsoft.yaml
        bash service.sh "apple icloud" apple &> ../service/apple.yaml
        bash service.sh "category-games" games bilibili &> ../service/games.yaml
        bash service.sh "category-games@cn" gamesCN &> ../service/gamesCN.yaml
        bash service.sh "youtube" entertainments &> ../service/youtube.yaml
        bash service.sh "geolocation-cn" cn &> ../service/cn.yaml
        bash service.sh "anthropic" &> ../service/anthropic.yaml
        bash service.sh "oracle"  &> ../service/oracle.yaml
        bash service.sh "github" &> ../service/github.yaml
        bash service.sh "eastmoney" &> ../service/eastmoney.yaml
        bash service.sh "momo" &> ../service/momo.yaml
        bash service.sh "kuaishou" &> ../service/kuaishou.yaml
        bash service.sh "bytedance" &> ../service/bytedance.yaml
        bash service.sh "youtube" &> ../service/youtube.yaml
        bash service.sh "category-public-tracker" &> ../service/tracker.yaml
        bash service.sh "cloudflare" &> ../service/cloudflare.yaml

        bash service.sh "telegram" &> ../service/telegram.yaml
        echo "   # ------ ipv4 ------>" >> ../service/telegram.yaml
        echo "   - IP-CIDR,67.198.55.0/24,no-resolve" >> ../service/telegram.yaml
        echo "   - IP-CIDR,91.108.4.0/22,no-resolve" >> ../service/telegram.yaml
        echo "   - IP-CIDR,91.108.8.0/22,no-resolve" >> ../service/telegram.yaml
        echo "   - IP-CIDR,91.108.12.0/22,no-resolve" >> ../service/telegram.yaml
        echo "   - IP-CIDR,91.108.16.0/22,no-resolve" >> ../service/telegram.yaml
        echo "   - IP-CIDR,91.108.20.0/22,no-resolve" >> ../service/telegram.yaml
        echo "   - IP-CIDR,91.108.56.0/22,no-resolve" >> ../service/telegram.yaml
        echo "   - IP-CIDR,109.239.140.0/24,no-resolve" >> ../service/telegram.yaml
        echo "   - IP-CIDR,149.154.160.0/20,no-resolve" >> ../service/telegram.yaml
        echo "   - IP-CIDR,149.154.164.0/22,no-resolve" >> ../service/telegram.yaml
        echo "   - IP-CIDR,149.154.168.0/22,no-resolve" >> ../service/telegram.yaml
        echo "   - IP-CIDR,149.154.172.0/22,no-resolve" >> ../service/telegram.yaml
        echo "   - IP-CIDR,185.76.151.0/24,no-resolve" >> ../service/telegram.yaml
        echo "   # ------ ipv6 ------>" >> ../service/telegram.yaml
        echo "   - IP-CIDR6,2001:67c:4e8::/48,no-resolve" >> ../service/telegram.yaml
        echo "   - IP-CIDR6,2001:b28:f23d::/48,no-resolve" >> ../service/telegram.yaml
        echo "   - IP-CIDR6,2001:b28:f23f::/48,no-resolve" >> ../service/telegram.yaml 
        echo "   - IP-CIDR6,2001:b28:f23c::/48,no-resolve" >> ../service/telegram.yaml 
        echo "   - IP-CIDR6,2a0a:f280::/32,no-resolve" >> ../service/telegram.yaml 



        echo "# Service: cloudflareip" > ../service/cloudflareip.yaml
        echo "# Repo: https://github.com/0xHO/WhiteList/blob/assets/service/cloudflareip.yaml" >> ../service/cloudflareip.yaml
        echo "# raw: https://raw.githubusercontent.com/0xHO/WhiteList/assets/service/cloudflareip.yaml" >> ../service/cloudflareip.yaml
        echo "# raw: https://cdn.jsdelivr.net/gh/0xHO/WhiteList@assets/service/cloudflareip.yaml" >> ../service/cloudflareip.yaml
        echo "# raw: https://ghproxy.com/https://raw.githubusercontent.com/0xHO/WhiteList/assets/service/cloudflareip.yaml" >> ../service/cloudflareip.yaml
        echo "# Update: ${today}" >> ../service/cloudflareip.yaml
        echo "payload:" >> ../service/cloudflareip.yaml
        curl -o ipv4.txt  https://www.cloudflare.com/ips-v4
        curl -o ipv6.txt  https://www.cloudflare.com/ips-v6
        echo "   # ------ ipv4 ------>" >> ../service/cloudflareip.yaml
        cat ipv4.txt |sed "s/^/   \- IP\-CIDR,/g" >> ../service/cloudflareip.yaml
        echo " " >> ../service/cloudflareip.yaml
        echo "   # ------ ipv6 ------>" >> ../service/cloudflareip.yaml
        cat ipv6.txt |sed "s/^/   \- IP\-CIDR6,/g" >> ../service/cloudflareip.yaml
        

        echo "# Service: gfw2" > ../service/gfw2.yaml
        echo "# Repo: https://github.com/0xHO/WhiteList/blob/assets/service/gfw2.yaml" >> ../service/gfw2.yaml
        echo "# raw: https://raw.githubusercontent.com/0xHO/WhiteList/assets/service/gfw2.yaml" >> ../service/gfw2.yaml
        echo "# raw: https://cdn.jsdelivr.net/gh/0xHO/WhiteList@assets/service/gfw2.yaml" >> ../service/gfw2.yaml
        echo "# raw: https://ghproxy.com/https://raw.githubusercontent.com/0xHO/WhiteList/assets/service/gfw2.yaml" >> ../service/gfw2.yaml
        echo "# Update: ${today}" >> ../service/gfw2.yaml
        echo "payload:" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,tw" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,us" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,tw" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,jp" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,sh" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,cc" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,io" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,me" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,xyz" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,uk" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,top" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,app" >> ../service/gfw2.yaml

        echo "   - DOMAIN-SUFFIX,bulianglin.com" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,v2rayssr.com" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,sehuatang.org" >> ../service/gfw2.yaml
        echo "   - DOMAIN-SUFFIX,instantfwding.com" >> ../service/gfw2.yaml
        
        echo "   - DOMAIN-KEYWORD,sehuatang" >> ../service/gfw2.yaml
        echo "   - DOMAIN-KEYWORD,1024" >> ../service/gfw2.yaml
        echo "   - DOMAIN-KEYWORD,t61y" >> ../service/gfw2.yaml
        echo "   - DOMAIN-KEYWORD,51fengliu" >> ../service/gfw2.yaml
        echo "   - DOMAIN-KEYWORD,tanhuaxiuchewang" >> ../service/gfw2.yaml
        

        cd ../
        git add service/*
        git commit WhiteList.txt ss.conf dnsmasq.conf -m "update WhiteList ${today}"
        git commit service/* -m "update Service ${today}"
        rm -rf main 

    - name: Push changes
      if: ( !cancelled() )
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: assets

    - name: Delete Workflow Runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 8
