name: WhiteList

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "35 20 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@main
      with:
        ref: assets
      
    - name: Clone domain list
      if: ( !cancelled() )
      id: clone
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        git config --local user.email "93760897+0xHO@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        cd /workdir
        git clone https://github.com/v2fly/domain-list-community  domainlist

    - name: Checkout Main Code
      if: ( !cancelled() )
      uses: actions/checkout@main
      with:
         path: main

    - name: Organize Files
      id: organize
      if: ( !cancelled() )
      run: |
        today=`date`
        ls -al
        ln -sf /workdir/domainlist main/domainlist
        cd main
        bash WhiteList.sh
        python3 -m base64 WhiteList.tmp &> ../WhiteList.txt
        cat ssc.tmp > ../ss.conf

        # bash service.sh "service file 
        bash service.sh "openai" &> ../service/openai.yaml
        bash service.sh "microsoft" microsoft "xbox\|github" &> ../service/microsoft.yaml
        bash service.sh "apple icloud" apple &> ../service/apple.yaml
        bash service.sh "category-games" games bilibili &> ../service/games.yaml
        bash service.sh "category-games@cn" gamesCN &> ../service/gamesCN.yaml
        bash service.sh "youtube" entertainments &> ../service/youtube.yaml
        bash service.sh "geolocation-cn" cn &> ../service/cn.yaml
        bash service.sh "anthropic" &> ../service/anthropic.yaml
        bash service.sh "oracle"  &> ../service/oracle.yaml
        bash service.sh "github" &> ../service/github.yaml
        bash service.sh "eastmoney" &> ../service/eastmoney.yaml
        bash service.sh "momo" &> ../service/momo.yaml
        bash service.sh "kuaishou" &> ../service/kuaishou.yaml
        bash service.sh "bytedance" &> ../service/bytedance.yaml
        bash service.sh "youtube" &> ../service/youtube.yaml
        bash service.sh "category-public-tracker" &> ../service/tracker.yaml
        bash service.sh "cloudflare" &> ../service/cloudflare.yaml
        curl -o ipv4.txt  https://www.cloudflare.com/ips-v4
        curl -o ipv6.txt  https://www.cloudflare.com/ips-v6
        echo "   # ------ cloudflare-ipv4 ------>" >> ../service/cloudflare.yaml
        cat ipv4.txt |sed "s/^/   \- IP\-CIDR,/g" >> ../service/cloudflare.yaml
        echo " " >> ../service/cloudflare.yaml
        echo "   # ------ cloudflare-ipv6 ------>" >> ../service/cloudflare.yaml
        cat ipv6.txt |sed "s/^/   \- IP\-CIDR6,/g" >> ../service/cloudflare.yaml
        

        cd ../
        git add service/*
        git commit WhiteList.txt ss.conf dnsmasq.conf -m "update WhiteList ${today}"
        git commit service/* -m "update Service ${today}"
        rm -rf main 

    - name: Push changes
      if: ( !cancelled() )
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: assets

    - name: Delete Workflow Runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 8
